# Generated by Selenium IDE + Customized with Headless + Logging
import pytest
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.firefox.options import Options

class TestTest1():
    def setup_method(self, method):
        print("🧪 Setup: Memulai Firefox dalam mode headless...")
        options = Options()
        options.add_argument("--headless")
        self.driver = webdriver.Firefox(options=options)
        self.driver.set_window_size(1280, 800)
        self.vars = {}

    def teardown_method(self, method):
        print("🧹 Teardown: Menutup browser.")
        self.driver.quit()

    def test_test1(self):
        print("🔗 Navigasi ke https://www.saucedemo.com/")
        self.driver.get("https://www.saucedemo.com/")

        print("🔐 Login dengan username dan password")
        self.driver.find_element(By.CSS_SELECTOR, "*[data-test='username']").send_keys("standard_user")
        self.driver.find_element(By.CSS_SELECTOR, "*[data-test='password']").send_keys("secret_sauce")
        self.driver.find_element(By.CSS_SELECTOR, "*[data-test='login-button']").click()

        print("🛒 Menambahkan semua produk ke keranjang")
        produk = [
            "add-to-cart-sauce-labs-backpack",
            "add-to-cart-sauce-labs-bike-light",
            "add-to-cart-sauce-labs-bolt-t-shirt",
            "add-to-cart-sauce-labs-fleece-jacket",
            "add-to-cart-sauce-labs-onesie",
            "add-to-cart-test.allthethings()-t-shirt-(red)"
        ]
        for item in produk:
            print(f"  ✅ Tambah produk: {item}")
            self.driver.find_element(By.CSS_SELECTOR, f"*[data-test='{item}']").click()

        print("🧾 Buka keranjang")
        self.driver.find_element(By.CSS_SELECTOR, "*[data-test='shopping-cart-link']").click()

        print("🗑️ Menghapus semua produk dari keranjang")
        for item in produk:
            remove_item = item.replace("add-to-cart", "remove")
            print(f"  ❌ Hapus produk: {remove_item}")
            self.driver.find_element(By.CSS_SELECTOR, f"*[data-test='{remove_item}']").click()

        print("🔄 Lanjutkan belanja")
        self.driver.find_element(By.CSS_SELECTOR, "*[data-test='continue-shopping']").click()

        print("🛒 Tambah satu produk kembali")
        self.driver.find_element(By.CSS_SELECTOR, "*[data-test='add-to-cart-sauce-labs-backpack']").click()

        print("🧾 Checkout proses")
        self.driver.find_element(By.CSS_SELECTOR, "*[data-test='shopping-cart-link']").click()
        self.driver.find_element(By.CSS_SELECTOR, "*[data-test='checkout']").click()
        self.driver.find_element(By.CSS_SELECTOR, "*[data-test='firstName']").send_keys("udin")
        self.driver.find_element(By.CSS_SELECTOR, "*[data-test='lastName']").send_keys("udin")
        self.driver.find_element(By.CSS_SELECTOR, "*[data-test='postalCode']").send_keys("1111")
        self.driver.find_element(By.CSS_SELECTOR, "*[data-test='continue']").click()

        print("✅ Selesaikan pesanan")
        self.driver.find_element(By.CSS_SELECTOR, "*[data-test='finish']").click()
        self.driver.find_element(By.CSS_SELECTOR, "*[data-test='back-to-products']").click()

        print("🚪 Logout dari aplikasi")
        self.driver.find_element(By.ID, "react-burger-menu-btn").click()
        time.sleep(1)  # beri delay sedikit untuk menu animasi
        self.driver.find_element(By.CSS_SELECTOR, "*[data-test='logout-sidebar-link']").click()
